name: Weekly Trend

on:
  schedule:
    - cron: '00 21 * * 5'   # 17:00 ET Friday
  workflow_dispatch:

jobs:
  trend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.x' }
      - run: pip install -r requirements.txt
      - run: python trend_script.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
          BOT_SECRET_TOKEN:  ${{ secrets.BOT_SECRET_TOKEN }}
